runtime: python38

entrypoint: gunicorn -b :$PORT --worker-class eventlet --workers 1 table_admin:app

# could use a B1 for 9h/day free
#instance_class: B1
#basic_scaling:
#  idle_timeout: 5m
#  max_instances: 1

# https://cloud.google.com/appengine/docs/standard#instance_classes
# https://cloud.google.com/appengine/docs/standard/python3/config/appref#scaling_elements
# or an F1 for 28h/day free - so could use an F2 14h/day or even F4 7h/day if needed
instance_class: F4_1G # still OOMs
automatic_scaling:
  min_instances: 0  # save money when unused
  max_instances: 1  # concurrency risk if more than 1
  max_idle_instances: 0  # $
  min_idle_instances: 0  # $
  max_concurrent_requests: 5  # i'm the only admin
  max_pending_latency:  15s  # 15s is max, card processing takes a while - todo do async?

# necessary for min_instances to work
inbound_services:
  - warmup

service: table-admin
