runtime: python311

entrypoint: gunicorn -b :$PORT --worker-class eventlet --workers 1 hello:app

# could use a B1 for 9h/day free
#instance_class: B1
#basic_scaling:
#  idle_timeout: 5m
#  max_instances: 1

# https://cloud.google.com/appengine/docs/standard#instance_classes
# https://cloud.google.com/appengine/docs/standard/python3/config/appref#scaling_elements
# or an F1 for 28h/day free - so could use an F2 14h/day or even F4 7h/day if needed
instance_class: F1
automatic_scaling:
  min_instances: 0  # save money when unused
  max_instances: 1  # concurrency risk if more than 1
  max_idle_instances: 0  # $
  min_idle_instances: 0  # $
  max_concurrent_requests: 50  # card game players can tolerate occasional load spikes
  max_pending_latency:  15s  # tiny server has slow startup

# necessary for min_instances to work
inbound_services:
  - warmup

service: default

handlers:
  - url: /favicon\.ico
    static_files: public/favicon.ico
    upload: public/favicon\.ico

  - url: /index\.html
    static_files: public/index.html
    upload: public/index\.html

  - url: /manifest\.json
    static_files: public/manifest.json
    upload: public/manifest\.json

  - url: /logo192\.png
    static_files: public/logo192.png
    upload: public/logo192\.png

  - url: /logo512\.png
    static_files: public/logo512.png
    upload: public/logo512\.png

    # I should figure out how to move the logos into the static/ directory

  - url: /robots\.txt
    static_files: public/robots.txt
    upload: public/robots\.txt

  - url: /static
    static_dir: public/static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
