runtime: python38

entrypoint: gunicorn -b :$PORT --worker-class eventlet --workers 1 hello:app

instance_class: B1

env_variables:
  CLOUD_STORAGE_BUCKET: clean-node-258400-bucket

basic_scaling:
  max_instances: 1   # concurrency risk if more than 1
  idle_timeout: 15m
