# constants
HAND = "Hand"
LIBRARY = "Library"
LOOK = "Look"  # TODO use for scry, look at top N, reveal, etc. Can display left of Hand in bottom bar.
GRAVEYARD = "Graveyard"
COMMAND_ZONE = "Command Zone"
EXILE = "Exile"
BATTLEFIELD = "Battlefield"
ZONES = [HAND, LIBRARY, LOOK, GRAVEYARD, COMMAND_ZONE, EXILE, BATTLEFIELD]

SHUFFLE_LIBRARY = 'SHUFFLE_LIBRARY'
MOVE_CARD = 'MOVE_CARD'
TOGGLE_TAP_CARD = 'TOGGLE_TAP_CARD'
TOGGLE_TRANSFORM_CARD = 'TOGGLE_TRANSFORM_CARD'
TOGGLE_FACEDOWN_CARD = 'TOGGLE_FACEDOWN_CARD'
UNTAP_ALL = 'UNTAP_ALL'
SET_PLAYER_COUNTER = 'SET_PLAYER_COUNTER'
SET_CARD_COUNTER = 'SET_CARD_COUNTER'
CREATE_TOKEN = 'CREATE_TOKEN'
MESSAGE = 'MESSAGE'
MULLIGAN = 'MULLIGAN'
